name: fuchsia_ctl
description: >
  A Dart package for paving, serving packages to, and running commands on a
  Fuchsia Device. This package is primarily intended for use in Flutter's
  continuous integration/testing infrastructure.
publish_to: none
repository: https://github.com/flutter/packages/tree/main/packages/fuchsia_ctl
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+fuchsia_ctl%22
version: 0.0.25

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  args: ^2.3.0
  file: ^6.0.0
  meta: ^1.1.7
  path: ^1.6.4
  process: ^4.2.4
  retry: ^3.0.0+1
  uuid: ^3.0.0

dev_dependencies:
  mockito: ^5.0.16
  test: ^1.15.5
